### ISSUE TITLE
[BE] [FEATURE] 관심목록 조회

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_BE#10]
## 설명
관심 목록 조회, 삭제 기능 구현

## To-do
- [x] DTO, ENTITY 작성
- [x] Controller, Service, Repository 작성
- [x] 관심 목록을 조회하는 로직 구현 및 테스트
- [x] RestContorller 구현 및 테스트

## ETC
TDD 개발입니다. 테스트 작성하셔야 합니다.

**Comment by ksostuft** [comment]
중복된 이슈가 발행되어 한 이슈를 닫습니다.
