### ISSUE TITLE
[BE] [FEATURE] 사용자제제 추가 기능 작업

### ISSUE THREAD

**Issue by 08166** [Merge-co/OIL-JANG_BE#125]
## 설명
* * *
사용자제제 기능 추가 작업진행하겠습니다
-  접수된 신고 처리 중 삭제 게시글이 5 개 이상일시 7일 정지 10개 이상일시 30일 정지 15개이상일시 영구 정지 입니다.
- 정지내용은 로그인 불가능입니다.

## To-do
* * *
- [x] 신고접수되어 관리자가 처리한 삭제 된 게시글, 유저고유번호, 상태값 조회 하여 삭제된 게시글 횟수 조회
- [x] 삭제된 게시글에대한 제제를 할 수 있도록 설정 (7일, 30, 영구정지)
- [x] 로그인 정지에 대한 기한 설정 정지 기한이 풀리면 다시 로그인 할 수 있도록 자동 설정
