### ISSUE TITLE
[BE] [FEATURE] CRUD 신고기능

### ISSUE THREAD

**Issue by lSuns** [Merge-co/OIL-JANG_BE#4]
## 설명
신고 조회, 등록, 삭제 기능 구현

## To-do

- [ ] DTO, ENTITY 작성
- [ ] Controller, Service, Repository구현
- [ ] 조회 로직 구현(신고정보, 다른테이블조인)

## ETC
TDD 개발입니다.
