### ISSUE TITLE
[BE] [FEATURE] 신고기능 조회

### ISSUE THREAD

**Issue by 08166** [Merge-co/OIL-JANG_BE#63]
## 설명
* * *
신고 기능 조회
## To-do
* * *
- [x] DTO, ENTITY 작성
- [x] Controller, Service, Repository 작성
- [x] 신고관리 조회하는 로직 구현 및 테스트
- [x] RestContorller 구현 및 테스트
