### ISSUE TITLE
[BE] [FEATURE] 신고기능 수정

### ISSUE THREAD

**Issue by 08166** [Merge-co/OIL-JANG_BE#65]
## 설명
* * *
신고기능 수정하기 
- 관리자가 신고 처리 

## To-do
* * *
- [x]  DTO, ENTITY 작성
- [x]  Controller, Service, Repository 작성
- [x]  조회 로직 구현(신고테이블에서 조회)
- [x]  신고 처리 수정 하는 로직 구현 및 테스트
- [x]  RestContorller 구현 및 테스트
