### ISSUE TITLE
[BE] [FEATURE] 상품 조회

### ISSUE THREAD

**Issue by ksostuft** [Merge-co/OIL-JANG_BE#9]
## 설명
상품 조회

## To-do

- [x] DTO, ENTITY 작성
- [x] Controller, Service, Repository 작성
- [x] 조회 로직 구현(상품 정보, 상품 이미지 정보, 다른 테이블에서 조인)
- [x] 상품 목록 조회 테스트 - 상품 썸네일까지
- [x] 상품 상세 조회 테스트 - 상품 상세 이미지들, 찜 여부까지
- [x] RestContorller 구현 및 테스트

## ETC
TDD 개발입니다. 테스트 작성하셔야 합니다.
